Repository PetHaha/PetHaha, pull requests merged in 2023-04, with the labels that each got.

#16 오류 수정, header 수정
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/service/MemberService2.java
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/webapp/header.jsp
  PetHaha/src/main/webapp/index.jsp
  PetHaha/src/main/webapp/member/memberUpdate.jsp
Labels: 버그, 수정

#17 Feat/login
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/controller/MemberController2.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/webapp/header.jsp
  PetHaha/src/main/webapp/member/memberUpdate.jsp
Labels: 수정

#18 add/ update menubar 추가
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/webapp/member/memberUpdate.jsp
Labels: 개발

#21 add/ 정보확인, 내가 쓴 글 확인
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/webapp/member/memberUpdate.jsp
  PetHaha/src/main/webapp/member/memberUpdateCheck.jsp
  PetHaha/src/main/webapp/member/myBoard.jsp
  PetHaha/src/main/webapp/member/myheader.jsp
Labels: 개발

#20 add/ 강아지, 고양이 게시판 구현
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/MemberController2.java
  PetHaha/src/main/resources/static/css/daeui.css
  PetHaha/src/main/webapp/board/dogcat.jsp
  PetHaha/src/main/webapp/board/paging2.jsp
  PetHaha/src/main/webapp/header.jsp
  PetHaha/src/main/webapp/index.jsp
Labels: 개발

#23 add/ 보드 글 상세 보기 jsp만들기
  PetHaha/src/main/java/pethaha/WebConfig.java
  PetHaha/src/main/java/pethaha/controller/MemberController2.java
  PetHaha/src/main/webapp/board/boardView.jsp
  PetHaha/src/main/webapp/board/dogcat.jsp
  PetHaha/src/main/webapp/index.jsp
Labels: 개발

#24 add/ 메세지 기능 데이터베이스
  PetHaha/PetHaha ERM.sql
  PetHaha/database/PetDb.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/webapp/member/myMsg_R.jsp
  PetHaha/src/main/webapp/member/myMsg_S.jsp
Labels: 개발

#25 add/ boardview 화면 구성
  PetHaha/src/main/resources/static/css/daeui.css
  PetHaha/src/main/webapp/board/boardView.jsp
Labels: 개발

#26 add/ 보낸-받은 메세지 기능 구현
  PetHaha/database/PetDb.sql
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/resources/static/images/opened.png
  PetHaha/src/main/resources/static/images/unopened.png
  PetHaha/src/main/webapp/member/myMsg_R.jsp
  PetHaha/src/main/webapp/member/myMsg_S.jsp
  PetHaha/src/main/webapp/member/myheader.jsp
Labels: 개발

#27 feat/ 보드 뷰 구현 & 댓글쓰기 작업 추가
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/BoardController2.java
  PetHaha/src/main/java/pethaha/controller/MemberController2.java
  PetHaha/src/main/java/pethaha/dao/IBoardDao2.java
  PetHaha/src/main/java/pethaha/dto/BoardVO.java
  PetHaha/src/main/java/pethaha/dto/MemberVO.java
  PetHaha/src/main/java/pethaha/dto/ReplyVO.java
  PetHaha/src/main/java/pethaha/service/BoardService2.java
  PetHaha/src/main/java/pethaha/service/MemberService2.java
  PetHaha/src/main/resources/mybatis/mapper/BoardDao2.xml
  PetHaha/src/main/resources/static/css/daeui.css
  PetHaha/src/main/resources/static/images/profile/noimg.jpg
  PetHaha/src/main/webapp/board/boardView.jsp
  PetHaha/src/main/webapp/board/dogcat.jsp
  PetHaha/src/main/webapp/images/profile/저에용.jpg
  PetHaha/src/main/webapp/images/profile/저에용1.jpg
  PetHaha/src/main/webapp/index.jsp
  PetHaha/src/main/webapp/member/memberUpdate.jsp
Labels: 개발

#29 feat/ 게시글 댓글 리스트
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/BoardController2.java
  PetHaha/src/main/java/pethaha/dao/IBoardDao2.java
  PetHaha/src/main/java/pethaha/dto/ReplyVO.java
  PetHaha/src/main/java/pethaha/service/BoardService2.java
  PetHaha/src/main/resources/mybatis/mapper/BoardDao2.xml
  PetHaha/src/main/webapp/board/boardView.jsp
Labels: 개발

#30 modify/ 보낸- 받은 메세지 버튼 변경
  PetHaha/src/main/webapp/member/msgDetail.jsp
Labels: 수정

#33 feat/ BoardView 댓글 작성/ 삭제 기능 추가
  PetHaha/PetHaha ERM.sql
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/BoardController2.java
  PetHaha/src/main/java/pethaha/dao/IBoardDao2.java
  PetHaha/src/main/java/pethaha/service/BoardService2.java
  PetHaha/src/main/resources/mybatis/mapper/BoardDao2.xml
  PetHaha/src/main/resources/static/css/daeui.css
  PetHaha/src/main/webapp/board/boardView.jsp
  PetHaha/src/main/webapp/board/dogcat.jsp
  PetHaha/src/main/webapp/index.jsp
Labels: 개발

#34 Feat/ 메세지 삭제 및 닉네임 체크 기능
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/webapp/member/msgDetail.jsp
  PetHaha/src/main/webapp/member/msgWrite.jsp
Labels: 개발

#35 Feat/좋아요 기능 추가
  PetHaha/PetHaha ERM.sql
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/BoardController2.java
  PetHaha/src/main/java/pethaha/dao/IBoardDao2.java
  PetHaha/src/main/java/pethaha/service/BoardService2.java
  PetHaha/src/main/resources/mybatis/mapper/BoardDao2.xml
  PetHaha/src/main/webapp/board/boardView.jsp
Labels: 개발

#37 Modify/ 메세지 답장보내기 버튼 수정
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/resources/static/images/gotmsg.png
  PetHaha/src/main/webapp/header.jsp
  PetHaha/src/main/webapp/member/msgDetail.jsp
  PetHaha/src/main/webapp/member/msgWrite.jsp
Labels: 수정

#38 Feat/ 마이페이지 - 내가 쓴 댓글 열람
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/webapp/images/profile/1004.jpg
  PetHaha/src/main/webapp/member/memberIdCheck.jsp
  PetHaha/src/main/webapp/member/memberJoin.jsp
  PetHaha/src/main/webapp/member/myBoard.jsp
  PetHaha/src/main/webapp/member/myReply.jsp
Labels: 개발

#39 Feat/ 닉네임 중복 확인 기능 구현
  PetHaha/database/이진.sql
  PetHaha/src/main/resources/static/css/pethaha.css
  PetHaha/src/main/webapp/member/memberIdCheck.jsp
  PetHaha/src/main/webapp/member/memberJoin.jsp
  PetHaha/src/main/webapp/member/memberNickCheck.jsp
Labels: 개발, 수정

#41 Feat/ 메세지 상단 아이콘 기능 구현
  PetHaha/database/이진.sql
  PetHaha/src/main/java/pethaha/controller/MemberController.java
  PetHaha/src/main/java/pethaha/dao/IMemberDao.java
  PetHaha/src/main/java/pethaha/service/MemberService.java
  PetHaha/src/main/resources/mybatis/mapper/MemberDao.xml
  PetHaha/src/main/resources/static/images/gotmsg.png
  PetHaha/src/main/webapp/header.jsp
Labels: 기획

#36 Feat/ 게시글 신고 팝업 띄우기
  PetHaha/PetHaha ERM.sql
  PetHaha/database/대의.sql
  PetHaha/src/main/java/pethaha/controller/BoardController2.java
  PetHaha/src/main/java/pethaha/dao/IBoardDao2.java
  PetHaha/src/main/java/pethaha/dto/ReportVO.java
  PetHaha/src/main/java/pethaha/service/BoardService2.java
  PetHaha/src/main/resources/mybatis/mapper/BoardDao2.xml
  PetHaha/src/main/webapp/board/boardView.jsp
  PetHaha/src/main/webapp/board/boardpolice.jsp
  PetHaha/src/main/webapp/member/memberUpdate.jsp
Labels: 개발
